# Generated by Django 3.0.8 on 2020-07-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200719_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Source'),
        ),
    ]
