# Generated by Django 3.0.8 on 2020-07-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200720_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(default=0, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='articles.Source'),
            preserve_default=False,
        ),
    ]
