# Generated by Django 3.1.2 on 2020-10-21 06:37

from django.db import migrations


def lowercase_source_name(apps, schema_editor):
    Source = apps.get_model('articles', 'Source')
    for source in Source.objects.all():
        source.name = source.name.lower()
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20201021_0148'),
    ]

    operations = [
        migrations.RunPython(lowercase_source_name),
    ]
