# Generated by Django 3.1.2 on 2020-10-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20201021_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
