# Generated by Django 3.0.8 on 2020-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200728_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
