# Generated by Django 3.0.8 on 2020-10-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201014_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='articles.Source'),
        ),
    ]
