# Generated by Django 3.1.2 on 2020-10-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201016_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIReponse',
            new_name='ApiResponse',
        ),
    ]
